// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracticoOrm;

#nullable disable

namespace PracticoOrm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616023908_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PracticoOrm.Models.DetalleReceta", b =>
                {
                    b.Property<int>("DetalleRecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detalle_receta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleRecetaId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cantidad");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("integer")
                        .HasColumnName("ingrediente_id");

                    b.Property<int>("RecetaId")
                        .HasColumnType("integer")
                        .HasColumnName("receta_id");

                    b.HasKey("DetalleRecetaId")
                        .HasName("pk_detalle_recetas");

                    b.HasIndex("IngredienteId")
                        .HasDatabaseName("ix_detalle_recetas_ingrediente_id");

                    b.HasIndex("RecetaId")
                        .HasDatabaseName("ix_detalle_recetas_receta_id");

                    b.ToTable("detalle_recetas", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detalle_venta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleVentaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    b.HasKey("DetalleVentaId")
                        .HasName("pk_detalle_ventas");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_detalle_ventas_producto_id");

                    b.HasIndex("VentaId")
                        .HasDatabaseName("ix_detalle_ventas_venta_id");

                    b.ToTable("detalle_ventas", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ingrediente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredienteId"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IngredienteId")
                        .HasName("pk_ingredientes");

                    b.ToTable("ingredientes", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.Mostrador", b =>
                {
                    b.Property<int>("MostradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mostrador_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MostradorId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("PuntoDeVentaId")
                        .HasColumnType("integer")
                        .HasColumnName("punto_de_venta_id");

                    b.HasKey("MostradorId")
                        .HasName("pk_mostradores");

                    b.HasIndex("PuntoDeVentaId")
                        .HasDatabaseName("ix_mostradores_punto_de_venta_id");

                    b.ToTable("mostradores", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PorcentajeDeGanancia")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("porcentaje_de_ganancia");

                    b.Property<int>("RecetaId")
                        .HasColumnType("integer")
                        .HasColumnName("receta_id");

                    b.Property<int>("TipoProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_producto_id");

                    b.HasKey("ProductoId")
                        .HasName("pk_productos");

                    b.HasIndex("RecetaId")
                        .HasDatabaseName("ix_productos_receta_id");

                    b.HasIndex("TipoProductoId")
                        .HasDatabaseName("ix_productos_tipo_producto_id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.PuntoDeVenta", b =>
                {
                    b.Property<int>("PuntoDeVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("punto_de_venta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PuntoDeVentaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("PuntoDeVentaId")
                        .HasName("pk_punto_de_ventas");

                    b.ToTable("punto_de_ventas", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("receta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecetaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("RecetaId")
                        .HasName("pk_recetas");

                    b.ToTable("recetas", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.TipoProducto", b =>
                {
                    b.Property<int>("TipoProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_producto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoProductoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("TipoProductoId")
                        .HasName("pk_tipo_productos");

                    b.ToTable("tipo_productos", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VentaId"));

                    b.Property<DateTime>("FechaDeVenta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_venta");

                    b.Property<int>("MostradorId")
                        .HasColumnType("integer")
                        .HasColumnName("mostrador_id");

                    b.HasKey("VentaId")
                        .HasName("pk_ventas");

                    b.HasIndex("MostradorId")
                        .HasDatabaseName("ix_ventas_mostrador_id");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("PracticoOrm.Models.DetalleReceta", b =>
                {
                    b.HasOne("PracticoOrm.Models.Ingrediente", "Ingrediente")
                        .WithMany("DetalleRecetas")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_recetas_ingredientes_ingrediente_id");

                    b.HasOne("PracticoOrm.Models.Receta", "Receta")
                        .WithMany("DetalleRecetas")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_recetas_recetas_receta_id");

                    b.Navigation("Ingrediente");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("PracticoOrm.Models.DetalleVenta", b =>
                {
                    b.HasOne("PracticoOrm.Models.Producto", "Producto")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_ventas_productos_producto_id");

                    b.HasOne("PracticoOrm.Models.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_ventas_ventas_venta_id");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PracticoOrm.Models.Mostrador", b =>
                {
                    b.HasOne("PracticoOrm.Models.PuntoDeVenta", "PuntoDeVenta")
                        .WithMany("Mostradores")
                        .HasForeignKey("PuntoDeVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mostradores_punto_de_ventas_punto_de_venta_id");

                    b.Navigation("PuntoDeVenta");
                });

            modelBuilder.Entity("PracticoOrm.Models.Producto", b =>
                {
                    b.HasOne("PracticoOrm.Models.Receta", "Receta")
                        .WithMany("Productos")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productos_recetas_receta_id");

                    b.HasOne("PracticoOrm.Models.TipoProducto", "TipoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("TipoProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productos_tipo_productos_tipo_producto_id");

                    b.Navigation("Receta");

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("PracticoOrm.Models.Venta", b =>
                {
                    b.HasOne("PracticoOrm.Models.Mostrador", "Mostrador")
                        .WithMany("Ventas")
                        .HasForeignKey("MostradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_mostradores_mostrador_id");

                    b.Navigation("Mostrador");
                });

            modelBuilder.Entity("PracticoOrm.Models.Ingrediente", b =>
                {
                    b.Navigation("DetalleRecetas");
                });

            modelBuilder.Entity("PracticoOrm.Models.Mostrador", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("PracticoOrm.Models.Producto", b =>
                {
                    b.Navigation("DetalleVentas");
                });

            modelBuilder.Entity("PracticoOrm.Models.PuntoDeVenta", b =>
                {
                    b.Navigation("Mostradores");
                });

            modelBuilder.Entity("PracticoOrm.Models.Receta", b =>
                {
                    b.Navigation("DetalleRecetas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PracticoOrm.Models.TipoProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PracticoOrm.Models.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
