// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracticoOrm;

#nullable disable

namespace PracticoOrm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612014202_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PracticoOrm.Models.DetalleReceta", b =>
                {
                    b.Property<int>("DetalleRecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleRecetaId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("integer");

                    b.Property<int>("RecetaId")
                        .HasColumnType("integer");

                    b.HasKey("DetalleRecetaId");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("RecetaId");

                    b.ToTable("DetalleRecetas");
                });

            modelBuilder.Entity("PracticoOrm.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleVentaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("DetalleVentaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("PracticoOrm.Models.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredienteId"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IngredienteId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("PracticoOrm.Models.Mostrador", b =>
                {
                    b.Property<int>("MostradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MostradorId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PuntoDeVentaId")
                        .HasColumnType("integer");

                    b.HasKey("MostradorId");

                    b.HasIndex("PuntoDeVentaId");

                    b.ToTable("Mostradores");
                });

            modelBuilder.Entity("PracticoOrm.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PorcentajeDeGanancia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RecetaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoProductoId")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId");

                    b.HasIndex("RecetaId");

                    b.HasIndex("TipoProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("PracticoOrm.Models.PuntoDeVenta", b =>
                {
                    b.Property<int>("PuntoDeVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PuntoDeVentaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PuntoDeVentaId");

                    b.ToTable("PuntoDeVentas");
                });

            modelBuilder.Entity("PracticoOrm.Models.Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecetaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RecetaId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("PracticoOrm.Models.TipoProducto", b =>
                {
                    b.Property<int>("TipoProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoProductoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TipoProductoId");

                    b.ToTable("TipoProductos");
                });

            modelBuilder.Entity("PracticoOrm.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VentaId"));

                    b.Property<DateTime>("FechaDeVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MostradorId")
                        .HasColumnType("integer");

                    b.HasKey("VentaId");

                    b.HasIndex("MostradorId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("PracticoOrm.Models.DetalleReceta", b =>
                {
                    b.HasOne("PracticoOrm.Models.Ingrediente", "Ingrediente")
                        .WithMany("DetalleRecetas")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticoOrm.Models.Receta", "Receta")
                        .WithMany("DetalleRecetas")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("PracticoOrm.Models.DetalleVenta", b =>
                {
                    b.HasOne("PracticoOrm.Models.Producto", "Producto")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticoOrm.Models.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PracticoOrm.Models.Mostrador", b =>
                {
                    b.HasOne("PracticoOrm.Models.PuntoDeVenta", "PuntoDeVenta")
                        .WithMany("Mostradores")
                        .HasForeignKey("PuntoDeVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoDeVenta");
                });

            modelBuilder.Entity("PracticoOrm.Models.Producto", b =>
                {
                    b.HasOne("PracticoOrm.Models.Receta", "Receta")
                        .WithMany("Productos")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticoOrm.Models.TipoProducto", "TipoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("TipoProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("PracticoOrm.Models.Venta", b =>
                {
                    b.HasOne("PracticoOrm.Models.Mostrador", "Mostrador")
                        .WithMany("Ventas")
                        .HasForeignKey("MostradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mostrador");
                });

            modelBuilder.Entity("PracticoOrm.Models.Ingrediente", b =>
                {
                    b.Navigation("DetalleRecetas");
                });

            modelBuilder.Entity("PracticoOrm.Models.Mostrador", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("PracticoOrm.Models.Producto", b =>
                {
                    b.Navigation("DetalleVentas");
                });

            modelBuilder.Entity("PracticoOrm.Models.PuntoDeVenta", b =>
                {
                    b.Navigation("Mostradores");
                });

            modelBuilder.Entity("PracticoOrm.Models.Receta", b =>
                {
                    b.Navigation("DetalleRecetas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PracticoOrm.Models.TipoProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PracticoOrm.Models.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
